relativeURLs = true
title = "Krystian Bua"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Student in Economics, Sant'Anna School of Advanced Studies, Pisa"
    logo = "kry_profile.jpg" 
    
